# ./docker-compose.yml

version: '3'

services:
  database:
    image: kartoza/postgis
    container_name: database
    environment:
      # POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DB: meditect
      POSTGRES_USER: meditect
      POSTGRES_PASSWORD: meditect
    ports:
      - "9906:5432"
      # - "9906:3306"

  adminer:
    image: adminer
    ports:
      - 8888:8080

  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8101:80"
    stdin_open: true
    tty: true

  nuxt:
    build: ./app/
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"

  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - "8100:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt